### ISSUE TITLE
Can't cd to the mountpoint.

### ISSUE THREAD

**Issue by victormuse** [saltstack/salt-fuse#9]
I've just installed salt-fuse, mounted and the first observation is that it does not go to background. That is not a stopper, but it is not consistent with what I expect from a mount.
The bug: this happens when I try to cd into the mounted directory (in another session):

```
# cd salt/
bash: cd: salt/: Bad address
```

And this shows in the session where salt-fuse is running:

```
]# salt-fuse salt
No minions matched the target. No command was sent, no jid was assigned.
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/fuse.py", line 414, in _wrapper
    return func(*args, **kwargs) or 0
  File "/usr/lib/python2.6/site-packages/fuse.py", line 636, in access
    return self.operations('access', path.decode(self.encoding), amode)
  File "/usr/lib/python2.6/site-packages/fuse.py", line 881, in __call__
    ret = getattr(self, op)(path, *args)
  File "/usr/lib/python2.6/site-packages/saltfuse/driver.py", line 84, in access
    'mode': mode,
  File "/usr/lib/python2.6/site-packages/saltfuse/driver.py", line 74, in _salt_cmd
    return ret[minion_id]
KeyError: u''
```

However, `cp` and `ls` seem to work fine. Here are the versions info:

```
# salt-fuse --versions-report
 Salt Fuse: 0.4.0
    Python: 2.6.9 (unknown, Mar 28 2014, 00:06:37)
      Salt: 2014.1.1
    FusePy: 2.0.2
# salt --versions-report
           Salt: 2014.1.1
         Python: 2.6.9 (unknown, Mar 28 2014, 00:06:37)
         Jinja2: 2.6
       M2Crypto: 0.20.2
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 2.2.0.1
            ZMQ: 3.2.4
```

**Comment by rallytime** [comment]
This repo is deprecated and the repo is archived. Therefore, this issue is now closed. Thank you.
